-- 删除重复数据
DELETE
from T_IOM_RECORDINFO
WHERE (UUID) IN (SELECT UUID FROM T_IOM_RECORDINFO GROUP BY UUID HAVING COUNT(UUID) > 1)
  AND ROWID NOT IN (SELECT MIN(ROWID) FROM T_IOM_RECORDINFO GROUP BY UUID HAVING COUNT(*) > 1);